### PR TITLE
feat(home): add partnership and coorganizer logos

### PR DESCRIPTION
**Pull request by rockleona**
Adding logos at the bottom of homepage.

### CODE REVIEW

**Review by YenPeiChen07 — APPROVED** [review]
LGTM.

**Review by jack482653 — CHANGES_REQUESTED** [review]
It looks wired at phone 👀
CleanShot 2024-12-06 at 14 04 43

**Comment by rockleona** [comment]
> It looks wired at phone 👀 CleanShot 2024-12-06 at 14 04 43

Thanks @jack482653 ! I edited another commit already.

**Comment by chestercheng** [comment]
> It looks wired at phone 👀 CleanShot 2024-12-06 at 14 04 43

Could we arrange the co-organizer logos in multiple rows on the mobile version? Currently, they seem a bit crowded

**Comment by rockleona** [comment]
@chestercheng , it looks like this right now

image

**Review by chestercheng — APPROVED** [review]
LGTM

**Pull request merged**
