### PR TITLE
feat(menu): add previous conf and open on a new tab

### PR DESCRIPTION
**Pull request by rockleona**
This PR is originally opened at #16, it was closed since I rebased and a mistake was made in branch name, the last commit is to apply @jack482653 's suggestion which is [here](https://github.com/sciwork/swconf2024/pull/16#discussion_r1866189892)

### CODE REVIEW

**Review by YenPeiChen07 — APPROVED** [review]
LGTM.

**Review by jack482653 — APPROVED** [review]
It's ok but it will more flexible if `target="_blank"` can be passed from props.

**Comment by rockleona** [comment]
> It's ok but it will more flexible if `target="_blank"` can be passed from props.

I wrote two props in DrawerLink, is that make sense in React? (not really familiar with it)

**Comment by jack482653** [comment]
Actually it is not necessary to add `is_blank` prop. You pass `...props` at  https://github.com/sciwork/swconf2024/blob/f5e67da010854bd0723a3091a22bffd50dfa5f50/components/DrawerLink.tsx#L6

It make you pass any props from outside, so you can write this

```
<DrawerLink target="_blank" />
```

or 

```
<DrawerLink target="_self" />
```

However, it may cause property not declared, so we need to try.

**Comment by rockleona** [comment]
> Actually it is not necessary to add `is_blank` prop. You pass `...props` at
> 
> https://github.com/sciwork/swconf2024/blob/f5e67da010854bd0723a3091a22bffd50dfa5f50/components/DrawerLink.tsx#L6
> 
> It make you pass any props from outside, so you can write this
> 
> ```
> <DrawerLink target="_blank" />
> ```
> 
> or
> 
> ```
> <DrawerLink target="_self" />
> ```
> 
> However, it may cause property not declared, so we need to try.

I've tried this but do not work on my device.

**Review by chestercheng — APPROVED** [review]

**Comment by chestercheng** [comment]
> > Actually it is not necessary to add `is_blank` prop. You pass `...props` at
> > https://github.com/sciwork/swconf2024/blob/f5e67da010854bd0723a3091a22bffd50dfa5f50/components/DrawerLink.tsx#L6
> > 
> > It make you pass any props from outside, so you can write this
> > ```
> > <DrawerLink target="_blank" />
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > or
> > ```
> > <DrawerLink target="_self" />
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > However, it may cause property not declared, so we need to try.
> 
> I've tried this but do not work on my device.

I'm not very familiar with React, but since the style looks good and the function meets our expect, I think we can proceed with merging this PR

**Comment by jack482653** [comment]
> > Actually it is not necessary to add `is_blank` prop. You pass `...props` at
> > https://github.com/sciwork/swconf2024/blob/f5e67da010854bd0723a3091a22bffd50dfa5f50/components/DrawerLink.tsx#L6
> > 
> > It make you pass any props from outside, so you can write this
> > ```
> > <DrawerLink target="_blank" />
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > or
> > ```
> > <DrawerLink target="_self" />
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > However, it may cause property not declared, so we need to try.
> 
> I've tried this but do not work on my device.

Hmmmmm wired. I will try it later.

**Comment by jack482653** [comment]
@rockleona turns out I forgot to add `{...props}` in `NextLink` 🙈:

CleanShot 2024-12-06 at 23 57 57@2x

**Pull request merged**
