### PR TITLE
feat(project): update project description of pydoc-zhtw and add a new…

### PR DESCRIPTION
**Pull request by rockleona**

### CODE REVIEW

**Review by YenPeiChen07 — COMMENTED** [review]
Thanks, @rockleona. The content looks good to me. But I am curious that the format is special for the ReGLOSS meetup?
image

**Comment by rockleona** [comment]
> Thanks, @rockleona. The content looks good to me. But I am curious that the format is special for the ReGLOSS meetup? image


Do you mean the font weight at the description? I will fix it with a new commit, please wait for a minute.

**Review by YenPeiChen07 — APPROVED** [review]
LGTM.

**Review by YenPeiChen07 — APPROVED** [review]
Thanks, LGTM.

**Pull request merged**
